# -*- coding: utf-8 -*-
"""Coding Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMU_mNZfmj-GtZ0c1o7HQTXBBlBW8pMM
"""

# Write a Python Program for Fibonacci numbers.

def fibonacci(n):
    fib_sequence = [0, 1]
    while len(fib_sequence) < n:
        fib_sequence.append(fib_sequence[-1] + fib_sequence[-2])
    return fib_sequence[:n]

# Input number of terms
n = int(input("Enter the number of terms: "))

if n <= 0:
    print("Please enter a positive integer.")
else:
    print("Fibonacci sequence:")
    print(fibonacci(n))



