# -*- coding: utf-8 -*-
"""Coding Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMU_mNZfmj-GtZ0c1o7HQTXBBlBW8pMM
"""

# Write a Python Program to Illustrate Different Set Operations.

# Define two sets
E = {0, 2, 4, 6, 8}
N = {1, 2, 3, 4, 5}

# Union of E and N
print("Union of E and N is", E |N)

# Intersection of E and N
print("Intersection of E and N is", E & N)

# Difference of E and N
print("Difference of E and N is", E - N)

# Symmetric difference of E and N
print("Symmetric difference of E and N is", E ^ N)

