# -*- coding: utf-8 -*-
"""Coding Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMU_mNZfmj-GtZ0c1o7HQTXBBlBW8pMM
"""

# Write a Python program to print all positive numbers in a range.

def positive_numbers(lst):
    positive_numbers = [num for num in lst if num > 0]
    if positive_numbers:
        print("Output:", ', '.join(map(str, positive_numbers)))
    else:
        print("Output: No positive numbers found")

# Input list of numbers
list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

# Print positive numbers in list1
print("Input:", list1)
positive_numbers(list1)

# Print positive numbers in list2
print("Input:", list2)
positive_numbers(list2)



